import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Lang = "id" | "en";

const KEY = "gainchain.lang.v1";

const dict = {
  id: {
    "nav.dashboard": "Dashboard",
    "nav.log": "Log Workout",
    "nav.badges": "My Badges",
    "nav.nft": "NFT Badges",
    "nav.leaderboard": "Leaderboard",
    "nav.owner": "Owner",
    "nav.myGym": "My Gym",
    "nav.home": "Home",
    "nav.features": "Features",
    "nav.how": "How It Works",
    "nav.about": "About",
    "cta.connect": "Connect Wallet",
    "cta.start": "Mulai Latihan",
    "cta.demo": "Lihat Demo",
    "cta.disconnect": "Disconnect",
    "lang.toggle": "EN",
    "role.title": "Pilih Role Lo",
    "role.subtitle": "Mau pakai GainChain sebagai apa?",
    "role.solo.title": "Gym Mandiri",
    "role.solo.desc": "Latihan sendiri, log workout, earn NFT badges.",
    "role.owner.title": "Punya Gym",
    "role.owner.desc": "Kelola member gym & terbitkan membership NFT.",
    "role.member.title": "Member Gym",
    "role.member.desc": "Anggota gym dengan membership NFT on-chain.",
    "role.continue": "Lanjut",
    "role.comingSoon": "Dalam Pengembangan",
    "landing.hero.badge": "On-Chain Fitness Proof Protocol",
    "landing.hero.titleTop": "Kerja Keras Lo di Gym",
    "landing.hero.titleMid": "Ga Bisa",
    "landing.hero.titleAccent": "Bohong.",
    "landing.hero.subtitle": "Tercatat Permanen di Solana Blockchain",
    "landing.hero.desc":
      "GainChain adalah platform Web3 pertama yang memverifikasi konsistensi latihan gym secara on-chain. Dapatkan NFT Achievement Badge sebagai bukti nyata dedikasi lo yang tidak dapat dipalsukan.",
    "landing.hero.live": "LIVE ON SOLANA MAINNET",
    "landing.hero.noSignup": "NO SIGN-UP NEEDED",
    "landing.stats.workouts": "Workouts Logged",
    "landing.stats.athletes": "Active Athletes",
    "landing.stats.badges": "NFT Badges Minted",
    "landing.problem.badge": "The Problem",
    "landing.problem.title": "Masalah Yang Kita Semua Tau",
    "landing.problem.solution": "Mengubah Itu Semua.",
    "landing.features.badge": "Features",
    "landing.features.title": "Fitur Utama GainChain",
    "landing.features.subtitle": "Semua yang lo butuh untuk prove your gains, on-chain.",
    "landing.how.badge": "Process",
    "landing.how.title": "Cara Kerjanya Simple",
    "landing.testimonials.badge": "Community",
    "landing.testimonials.title": "Athletes yang Udah Buktiin",
    "landing.cta.title": "Siap Buktiin Dedikasi Lo?",
    "landing.cta.desc": "Join ribuan athletes yang sudah mencatat perjalanan gym mereka di blockchain.",
    "landing.cta.button": "Connect Wallet & Mulai Sekarang",
    "landing.cta.powered": "POWERED BY SOLANA • GRATIS UNTUK MEMULAI",
    "footer.desc": "On-Chain Fitness Proof Protocol. Catat workout-mu permanen di Solana blockchain.",
    "footer.platform": "Platform",
    "footer.resources": "Resources",
    "footer.privacy": "Privacy Policy",
    "footer.copy": "© 2025 GainChain. Built on Solana Blockchain.",
    "footer.immutable": "All workout data is stored immutably on-chain",
    "dashboard.welcome": "Selamat datang, Athlete! 💪",
    "dashboard.logToday": "Log Workout Hari Ini",
    "dashboard.currentStreak": "Current Streak",
    "dashboard.totalWorkouts": "Total Workouts",
    "dashboard.totalVolume": "Total Volume",
    "dashboard.badgesEarned": "Badges Earned",
    "dashboard.quickLog.title": "Log Workout Hari Ini",
    "dashboard.quickLog.custom": "atau log custom workout →",
    "dashboard.progressSilver": "Progress ke Silver",
    "dashboard.progressSilverSub": "43 hari lagi untuk Silver Badge!",
    "dashboard.recentWorkouts": "Recent Workouts",
    "dashboard.calendar": "Streak Calendar",
    "logger.title": "Log Workout Baru",
    "logger.subtitle": "Catat sesi latihanmu — langsung permanen di Solana blockchain.",
    "logger.date": "Date",
    "logger.duration": "Duration (min)",
    "logger.type": "Workout Type",
    "logger.exercises": "Exercises",
    "logger.addExercise": "Add Exercise",
    "logger.notes": "Notes (optional)",
    "logger.notesPlaceholder": "Hari ini terasa kuat, dapat PR di bench...",
    "logger.confirming": "Confirming on Solana...",
    "logger.save": "Simpan ke Blockchain",
    "logger.tips": "Tips",
    "logger.history": "Workout History",
    "logger.error.cbum": "Ronnie Coleman / CBum validation failed — 1RM exceeds elite human limits. Log rejected.",
    "logger.peerValidation": "Request Peer-Validation (Web2.5)",
    "logger.peerValidation.title": "Peer-Validation Request",
    "logger.peerValidation.desc": "Share this link with a gym buddy or coach to validate your lift off-chain.",
    "logger.peerValidation.badge": "Validator earns +50 Shadow Points",
    "logger.peerValidation.share": "Share via WhatsApp",
    "logger.peerValidation.link": "Validation Link",
    "calibration.title": "Sport-Science Calibration",
    "calibration.desc": "Body weight is required exclusively for Smart-Contract Sport Science Calibration. Your 1RM limits and anti-cheat thresholds are computed from this value.",
    "calibration.privacy": "No name or username required — your wallet address is your identity. Weight data stays local and is never published on-chain.",
    "calibration.weightLabel": "Body Weight (kg)",
    "calibration.submit": "Complete Calibration",
    "calibration.calibrating": "Calibrating...",
    "calibration.success": "Calibration complete — welcome to GainChain!",
    "calibration.error.invalid": "Enter a valid body weight between 30–300 kg.",
    "badges.title": "Badge Pencapaian Saya",
    "badges.tier.bronze": "Bronze",
    "badges.tier.silver": "Silver",
    "badges.tier.gold": "Gold",
    "badges.tier.platinum": "Platinum",
    "badges.tier.diamond": "Diamond",
    "badges.category.streak": "Consistency Streaks",
    "badges.category.volume": "Total Volume",
    "badges.category.mastery": "Lift Mastery",
    "owner.pendingClaims": "Pending Challenge Claims",
    "owner.pendingClaimsSub": "Members requesting validation for gym events",
    "owner.approve": "Approve",
    "owner.reject": "Reject",
    "owner.approveSuccess": "NFT mint simulated — claim approved!",
    "owner.rejectSuccess": "Claim rejected.",
    "badges.earned": "Earned",
    "badges.locked": "Locked",
    "badges.viewSolana": "View on Solana",
    "badges.requirement": "Requirement",
    "badges.progress": "PROGRESS",
    "badges.rarity": "Rarity",
    "leaderboard.title": "Leaderboard",
    "leaderboard.subtitle": "Athletes paling konsisten di GainChain.",
    "leaderboard.timeframe": "Timeframe",
    "leaderboard.category": "Category",
    "leaderboard.rankings": "Full Rankings",
    "leaderboard.rank": "Rank",
    "leaderboard.athlete": "Athlete",
    "leaderboard.badge": "Badge",
    "leaderboard.streak": "Streak",
    "leaderboard.workouts": "Workouts",
    "owner.title": "Gym Owner Dashboard",
    "owner.quickAction": "Quick Action",
    "owner.memberManagement": "Member Management",
    "owner.memberManagementSub": "Kelola semua member gym-mu",
    "owner.searchWallet": "Cari wallet…",
    "owner.noMember": "Tidak ada member yang cocok.",
    "owner.quickActions": "Quick Actions",
    "owner.gymLeaderboard": "Gym Leaderboard",
    "owner.top5Month": "Top 5 bulan ini",
    "member.titleSuffix": "Member Dashboard",
    "member.memberSince": "Member since",
    "member.smartMembership": "Smart Membership NFT",
    "member.active": "ACTIVE",
    "member.tokenId": "Token ID",
    "member.activeUntil": "Active Until",
    "member.contract": "Contract",
    "member.verifiedSolana": "Verified on Solana Mainnet",
    "member.viewExplorer": "View on Solana Explorer",
    "member.verifiedGym": "Verified Gym Partner",
    "member.members": "Members",
    "member.location": "Location",
    "member.status": "Status",
    "member.visitGym": "Visit Gym Page",
    "member.myStreak": "My Streak",
    "member.myRank": "My Rank in Gym",
    "member.workoutsMonth": "Workouts This Month",
    "member.nextBadge": "Next Badge",
    "member.leaderboardGym": "Leaderboard",
    "member.top10": "Top 10 member by streak",
    "member.thisMonth": "This Month",
    "member.you": "YOU",
    "member.activeChallenges": "Active Gym Challenges",
    "member.live": "LIVE",
    "member.ends": "Ends",
    "member.prize": "Prize",
    "member.joinChallenge": "Join Challenge",
    "onboarding.step": "ONBOARDING • STEP",
    "onboarding.of": "OF",
    "onboarding.welcome": "Selamat Datang di",
    "onboarding.chooseStart": "Pilih bagaimana kamu mau memulai journey blockchain fitness-mu",
    "onboarding.solo.title": "Saya Gym Mandiri",
    "onboarding.solo.desc": "Log workout sendiri, earn NFT badges, track progress personal.",
    "onboarding.owner.title": "Saya Punya Gym",
    "onboarding.owner.desc": "Kelola member gym, terbitkan membership NFT, buat challenges.",
    "onboarding.chooseThis": "Pilih ini",
    "onboarding.powered": "Powered by Solana • You can change this later",
    "onboarding.setupAthlete": "Setup Profile Atletmu",
    "onboarding.personalize": "Personalisasi journey-mu. Data ini akan dilink ke wallet-mu.",
    "onboarding.goal": "Fitness Goal",
    "onboarding.level": "Experience Level",
    "onboarding.program": "Preferred Program",
    "onboarding.back": "Kembali",
    "onboarding.start": "Mulai Journey",
    "onboarding.registerGym": "Daftarkan Gym Lo",
    "onboarding.registerDesc": "Info ini akan disimpan on-chain dan ditampilkan ke calon member.",
    "onboarding.gymName": "Gym Name",
    "onboarding.location": "Location",
    "onboarding.gymDesc": "Gym Description",
    "onboarding.capacity": "Member Capacity",
    "onboarding.price": "Membership Price (USDC / month)",
    "onboarding.register": "Daftarkan Gym",
    "notfound.message": "Oops! Page not found",
    "notfound.back": "Return to Home",
  },
  en: {
    "nav.dashboard": "Dashboard",
    "nav.log": "Log Workout",
    "nav.badges": "My Badges",
    "nav.nft": "NFT Badges",
    "nav.leaderboard": "Leaderboard",
    "nav.owner": "Owner",
    "nav.myGym": "My Gym",
    "nav.home": "Home",
    "nav.features": "Features",
    "nav.how": "How It Works",
    "nav.about": "About",
    "cta.connect": "Connect Wallet",
    "cta.start": "Start Training",
    "cta.demo": "Watch Demo",
    "cta.disconnect": "Disconnect",
    "lang.toggle": "ID",
    "role.title": "Choose Your Role",
    "role.subtitle": "How will you use GainChain?",
    "role.solo.title": "Solo Athlete",
    "role.solo.desc": "Train solo, log workouts, earn NFT badges.",
    "role.owner.title": "Gym Owner",
    "role.owner.desc": "Manage gym members & issue membership NFTs.",
    "role.member.title": "Gym Member",
    "role.member.desc": "Gym member with on-chain membership NFT.",
    "role.continue": "Continue",
    "role.comingSoon": "Coming Soon",
    "landing.hero.badge": "On-Chain Fitness Proof Protocol",
    "landing.hero.titleTop": "Your Hard Work at the Gym",
    "landing.hero.titleMid": "Can't Be",
    "landing.hero.titleAccent": "Faked.",
    "landing.hero.subtitle": "Permanently Recorded on Solana Blockchain",
    "landing.hero.desc":
      "GainChain is the first Web3 platform that verifies gym training consistency on-chain. Earn NFT Achievement Badges as immutable proof of your dedication.",
    "landing.hero.live": "LIVE ON SOLANA MAINNET",
    "landing.hero.noSignup": "NO SIGN-UP NEEDED",
    "landing.stats.workouts": "Workouts Logged",
    "landing.stats.athletes": "Active Athletes",
    "landing.stats.badges": "NFT Badges Minted",
    "landing.problem.badge": "The Problem",
    "landing.problem.title": "The Problem We All Know",
    "landing.problem.solution": "Changes Everything.",
    "landing.features.badge": "Features",
    "landing.features.title": "Core GainChain Features",
    "landing.features.subtitle": "Everything you need to prove your gains, on-chain.",
    "landing.how.badge": "Process",
    "landing.how.title": "How It Works",
    "landing.testimonials.badge": "Community",
    "landing.testimonials.title": "Athletes Who Proved It",
    "landing.cta.title": "Ready to Prove Your Dedication?",
    "landing.cta.desc": "Join thousands of athletes who already log their gym journey on the blockchain.",
    "landing.cta.button": "Connect Wallet & Start Now",
    "landing.cta.powered": "POWERED BY SOLANA • FREE TO START",
    "footer.desc": "On-Chain Fitness Proof Protocol. Record your workouts permanently on Solana blockchain.",
    "footer.platform": "Platform",
    "footer.resources": "Resources",
    "footer.privacy": "Privacy Policy",
    "footer.copy": "© 2025 GainChain. Built on Solana Blockchain.",
    "footer.immutable": "All workout data is stored immutably on-chain",
    "dashboard.welcome": "Welcome back, Athlete! 💪",
    "dashboard.logToday": "Log Today's Workout",
    "dashboard.currentStreak": "Current Streak",
    "dashboard.totalWorkouts": "Total Workouts",
    "dashboard.totalVolume": "Total Volume",
    "dashboard.badgesEarned": "Badges Earned",
    "dashboard.quickLog.title": "Log Today's Workout",
    "dashboard.quickLog.custom": "or log custom workout →",
    "dashboard.progressSilver": "Progress to Silver",
    "dashboard.progressSilverSub": "43 days to go for Silver Badge!",
    "dashboard.recentWorkouts": "Recent Workouts",
    "dashboard.calendar": "Streak Calendar",
    "logger.title": "Log New Workout",
    "logger.subtitle": "Record your training session and store it permanently on Solana blockchain.",
    "logger.date": "Date",
    "logger.duration": "Duration (min)",
    "logger.type": "Workout Type",
    "logger.exercises": "Exercises",
    "logger.addExercise": "Add Exercise",
    "logger.notes": "Notes (optional)",
    "logger.notesPlaceholder": "Felt strong today, hit a PR on bench...",
    "logger.confirming": "Confirming on Solana...",
    "logger.save": "Save to Blockchain",
    "logger.tips": "Tips",
    "logger.history": "Workout History",
    "logger.error.cbum": "Ronnie Coleman / CBum validation failed — 1RM exceeds elite human limits. Log rejected.",
    "logger.peerValidation": "Request Peer-Validation (Web2.5)",
    "logger.peerValidation.title": "Peer-Validation Request",
    "logger.peerValidation.desc": "Share this link with a gym buddy or coach to validate your lift off-chain.",
    "logger.peerValidation.badge": "Validator earns +50 Shadow Points",
    "logger.peerValidation.share": "Share via WhatsApp",
    "logger.peerValidation.link": "Validation Link",
    "calibration.title": "Sport-Science Calibration",
    "calibration.desc": "Body weight is required exclusively for Smart-Contract Sport Science Calibration. Your 1RM limits and anti-cheat thresholds are computed from this value.",
    "calibration.privacy": "No name or username required — your wallet address is your identity. Weight data stays local and is never published on-chain.",
    "calibration.weightLabel": "Body Weight (kg)",
    "calibration.submit": "Complete Calibration",
    "calibration.calibrating": "Calibrating...",
    "calibration.success": "Calibration complete — welcome to GainChain!",
    "calibration.error.invalid": "Enter a valid body weight between 30–300 kg.",
    "badges.title": "My Achievement Badges",
    "badges.tier.bronze": "Bronze",
    "badges.tier.silver": "Silver",
    "badges.tier.gold": "Gold",
    "badges.tier.platinum": "Platinum",
    "badges.tier.diamond": "Diamond",
    "badges.category.streak": "Consistency Streaks",
    "badges.category.volume": "Total Volume",
    "badges.category.mastery": "Lift Mastery",
    "owner.pendingClaims": "Pending Challenge Claims",
    "owner.pendingClaimsSub": "Members requesting validation for gym events",
    "owner.approve": "Approve",
    "owner.reject": "Reject",
    "owner.approveSuccess": "NFT mint simulated — claim approved!",
    "owner.rejectSuccess": "Claim rejected.",
    "badges.earned": "Earned",
    "badges.locked": "Locked",
    "badges.viewSolana": "View on Solana",
    "badges.requirement": "Requirement",
    "badges.progress": "PROGRESS",
    "badges.rarity": "Rarity",
    "leaderboard.title": "Leaderboard",
    "leaderboard.subtitle": "The most consistent athletes on GainChain.",
    "leaderboard.timeframe": "Timeframe",
    "leaderboard.category": "Category",
    "leaderboard.rankings": "Full Rankings",
    "leaderboard.rank": "Rank",
    "leaderboard.athlete": "Athlete",
    "leaderboard.badge": "Badge",
    "leaderboard.streak": "Streak",
    "leaderboard.workouts": "Workouts",
    "owner.title": "Gym Owner Dashboard",
    "owner.quickAction": "Quick Action",
    "owner.memberManagement": "Member Management",
    "owner.memberManagementSub": "Manage all your gym members",
    "owner.searchWallet": "Search wallet…",
    "owner.noMember": "No matching members found.",
    "owner.quickActions": "Quick Actions",
    "owner.gymLeaderboard": "Gym Leaderboard",
    "owner.top5Month": "Top 5 this month",
    "member.titleSuffix": "Member Dashboard",
    "member.memberSince": "Member since",
    "member.smartMembership": "Smart Membership NFT",
    "member.active": "ACTIVE",
    "member.tokenId": "Token ID",
    "member.activeUntil": "Active Until",
    "member.contract": "Contract",
    "member.verifiedSolana": "Verified on Solana Mainnet",
    "member.viewExplorer": "View on Solana Explorer",
    "member.verifiedGym": "Verified Gym Partner",
    "member.members": "Members",
    "member.location": "Location",
    "member.status": "Status",
    "member.visitGym": "Visit Gym Page",
    "member.myStreak": "My Streak",
    "member.myRank": "My Gym Rank",
    "member.workoutsMonth": "Workouts This Month",
    "member.nextBadge": "Next Badge",
    "member.leaderboardGym": "Leaderboard",
    "member.top10": "Top 10 members by streak",
    "member.thisMonth": "This Month",
    "member.you": "YOU",
    "member.activeChallenges": "Active Gym Challenges",
    "member.live": "LIVE",
    "member.ends": "Ends",
    "member.prize": "Prize",
    "member.joinChallenge": "Join Challenge",
    "onboarding.step": "ONBOARDING • STEP",
    "onboarding.of": "OF",
    "onboarding.welcome": "Welcome to",
    "onboarding.chooseStart": "Choose how you want to start your blockchain fitness journey",
    "onboarding.solo.title": "I'm a Solo Athlete",
    "onboarding.solo.desc": "Log your own workouts, earn NFT badges, and track personal progress.",
    "onboarding.owner.title": "I Own a Gym",
    "onboarding.owner.desc": "Manage members, issue membership NFTs, and create challenges.",
    "onboarding.chooseThis": "Choose this",
    "onboarding.powered": "Powered by Solana • You can change this later",
    "onboarding.setupAthlete": "Set Up Your Athlete Profile",
    "onboarding.personalize": "Personalize your journey. This data will be linked to your wallet.",
    "onboarding.goal": "Fitness Goal",
    "onboarding.level": "Experience Level",
    "onboarding.program": "Preferred Program",
    "onboarding.back": "Back",
    "onboarding.start": "Start Journey",
    "onboarding.registerGym": "Register Your Gym",
    "onboarding.registerDesc": "This info will be stored on-chain and shown to prospective members.",
    "onboarding.gymName": "Gym Name",
    "onboarding.location": "Location",
    "onboarding.gymDesc": "Gym Description",
    "onboarding.capacity": "Member Capacity",
    "onboarding.price": "Membership Price (USDC / month)",
    "onboarding.register": "Register Gym",
    "notfound.message": "Oops! Page not found",
    "notfound.back": "Return to Home",
  },
} as const;

type Key = keyof typeof dict["id"];

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  toggle: () => void;
  t: (k: Key) => string;
};

const LangCtx = createContext<Ctx>({
  lang: "id",
  setLang: () => {},
  toggle: () => {},
  t: (k) => k,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>("id");

  useEffect(() => {
    const stored = localStorage.getItem(KEY);
    if (stored === "id" || stored === "en") setLangState(stored);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem(KEY, l);
  };
  const toggle = () => setLang(lang === "id" ? "en" : "id");
  const t = (k: Key) => dict[lang][k] ?? k;

  return <LangCtx.Provider value={{ lang, setLang, toggle, t }}>{children}</LangCtx.Provider>;
};

export const useLang = () => useContext(LangCtx);
